// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtensionManager
{
    internal sealed partial class Vsix
    {
        public const string Id = "9cd6451c-c2fa-46fb-844a-a2535b824f1d";
        public const string Name = "Extension Manager 2017";
        public const string Description = @"Import/export extensions as well as associate extensions with individual solutions";
        public const string Language = "en-US";
        public const string Version = "9.9.9999";
        public const string Author = "Loop8ack";
        public const string Tags = "extension pack, vsix";
    }
}
