// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtensionManager
{
    internal sealed partial class Vsix
    {
        public const string Id = "3d183c28-64c6-4efb-a201-50310d65e675";
        public const string Name = "Extension Manager 2022";
        public const string Description = @"Import/export extensions as well as associate extensions with individual solutions";
        public const string Language = "en-US";
        public const string Version = "1.2.9999";
        public const string Author = "Loop8ack";
        public const string Tags = "extension pack, vsix";
    }
}
