// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtensionManager
{
    internal sealed partial class Vsix
    {
        public const string Id = "e886a834-bf5c-4bc6-aabe-ffad88b4dc6e";
        public const string Name = "Extension Manager 2019";
        public const string Description = @"Import/export extensions as well as associate extensions with individual solutions";
        public const string Language = "en-US";
        public const string Version = "9.9.9999";
        public const string Author = "Loop8ack";
        public const string Tags = "extension pack, vsix";
    }
}
