// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtensionManager
{
    internal sealed partial class Vsix
    {
        public const string Id = "4a196712-2c3f-4730-ad1d-e7cda4185eb2";
        public const string Name = "Extension Manager 2019";
        public const string Description = @"Import/export extensions as well as associate extensions with individual solutions";
        public const string Language = "en-US";
        public const string Version = "0.6.9999";
        public const string Author = "Mads Kristensen";
        public const string Tags = "extension pack, vsix";
    }
}
