// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtensionManager
{
				static class Vsix
				{
								public const string Id = "e83d71b8-8bfc-4e06-b145-b0388910c016";
								public const string Name = "Extension Manager";
								public const string Description = @"Import/export extensions as well as associate extensions with individual solutions";
								public const string Language = "en-US";
								public const string Version = "0.1";
								public const string Author = "Mads Kristensen";
								public const string Tags = "extension pack, vsix";
				}
}
