// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtensionPackTools
{
    static class Vsix
    {
        public const string Id = "e83d71b8-8bfc-4e06-b145-b0388910c016";
        public const string Name = "Extension Pack Tools";
        public const string Description = @"Tools for creating Visual Studio extension packs";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "extension pack, vsix";
    }
}
